### ISSUE TITLE
initSkjemanavn i klientbiblioteket mangler flere meldingsnavn

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/gi-plan#5]
ResultatOpprettArealplan og ResultatRegistrerDispensasjonFraPlan mangler iallefall.
Det er 31 meldinger i dictionarien og 40 meldingstyper, men jeg har ikke sjekket hvilke flere som mangler

**Comment by OlaStalberg** [comment]
Jeg oppdaterte en Nuget-pakke. 
Resultatschema for OpprettArealplan er no.ks.fiks.gi.plan.v2.oppdatering.meldingomplanident.resultat slik det står oppført i Wikien nå. Den skal finnes. 
For RegistrerdispensasjonFraPlan finnes no.ks.fiks.gi.plan.v2.oppdatering.dispensasjonplan.resultat.
Mange av meldingene går under [RegistrerPlanbehandling ](https://github.com/ks-no/gi-plan/wiki/Registrer-planbehandling) og har samme meldingstyper. Si fra om du kommer over noen andre eller om dette ikke løste manglene.

**Comment by Arve-Corneliussen** [comment]
Ja, skjemaene finnes, men funksjonen GetSkjemanavn klarer ikke å finne de fordi de ikke finnes i dictionarien du bygger opp

**Comment by OlaStalberg** [comment]
Vil du se om dette er blitt tilgjengeligjort nå i ny pakkeoppdatering?

**Comment by Arve-Corneliussen** [comment]
Det er tilgjengelig, GetSkjemanavn fungerer, tester embedded resource for skjema nå

**Comment by Arve-Corneliussen** [comment]
Testet OK
